kind: pipeline
type: docker
name: default

steps:
- name: 编译分支代码   
  image: juanchen03/newtest:1.0
  pull: always
  commands:
    - pwd
    - ls -la
    - npm install
    - ln -sfn /drone/node_modules node_modules
    - ls -la
    - npm run build
    - ls -la
    
  when:
    branch: main
    event: push
    
trigger:
  branch:
    include:
      - main
  event:
    include:
      - push
