kind: pipeline
type: docker
name: default

steps:
- name: build
  image: juanchen03/newtest:1.0
  pull: always
  commands:
    - pwd
    - ls -la
    - npm install
    - ln -sfn /drone/node_modules node_modules 
    - ls -la
    - npm run build
    - ls -la

- name: devlop
  image: juanchen03/drone-scp
  pull: always
  settings:
      host:
        from_secret: ssh_host
      username: 
        from_secret: ssh_name
      password: 
        from_secret: ssh_password
      target: /home/nginx/html # 把项目拷贝到target目录
      source: dist/* # 打包后的那个目录
      rm: true
      strip_components: 1
      script:
        - nginx -s reload
  when:
    branch: main
    event: push
    
    
trigger:
  branch:
    include:
      - main
  event:
    include:
      - push
