kind: pipeline
type: docker
name: default

steps:
- name: 编译分支代码
  image: juanchen03/newtest:1.0
  pull: always
  commands:
    - pwd
    - ls -la
    - npm install
    - ln -sfn /drone/node_modules node_modules 
    - ls -la
    - npm run build
    - ls -la

- name: devlop
  image: juanchen03/drone-scp
  pull: always
  settings:
      host:
        from_secret: 106.13.3.168 # 这里就是上面配的secret，也可以明文
      username: root # 登录名
      password: 
        from_secret: ABC911003abc # 登录密码
      command_timeout: 3m
      # 设置要将打包户的文件部署到的文件地址
      target: /usr/share/nginx/html # 把项目拷贝到target目录
      source: dist/* # 打包后的那个目录
      rm: true
      strip_components: 1
  when:
    branch: main
    event: push
    
    
trigger:
  branch:
    include:
      - main
  event:
    include:
      - push
