kind: pipeline
type: docker
name: default

steps:
- name: 编译分支代码  
  image: juanchen03/chenjuan:testing
  pull: always
  commands:
    - ls -la
    - ln -sfn /drone/node_modules node_modules
    - yarn build
    - ls -la
    - pwd
  when:
    branch: main
    event: push
    
trigger:
  branch:
    include:
      - main
  event:
    include:
      - push
