# kind 和 type 属性定义了一个 Kubernetes 管道
kind: pipeline
type: docker
name: default

steps:
- name: install && build
  image: drone/drone-runner-docker:1
  pull: always
  commands:
    - ls -la
    - ln -sfn /drone/node_modules node_modules
    - npm run build
    - ls -la
    - pwd
   when:
     branch: main
     event: push

- name: commands
  image: appleboy/drone-ssh
      
trigger:
  branch:
    include:
      - main
  event:
    include:
      - push
